name: Build macOS Package

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - run: bash build-mac.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        with:
          name: memo-macos
          path: |
            dist/*.dmg
            dist/*.app

      - run: ls -lh dist

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*.dmg
